services:
  - type: web
    name: ai-resume-backend
    env: node
    plan: free
    rootDir: ai-resume-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false  # set manually in the dashboard if not committing

  - type:  static_site
    name: ai-resume-frontend
    rootDir: AI_Resume_Optimizer
    buildCommand: npm install && npm run build
    staticPublishPath: dist  # or build if Create React App
    envVars:
      - key: VITE_API_URL
        value: https://ai-resume-backend.onrender.com
