services:
  - type: web
    name: ai-resume-backend
    env: node
    plan: free
    rootDir: ai-resume-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false  # or true if you set it in Render dashboard

  - type: web  # <- use web instead of static_site
    name: ai-resume-frontend
    env: static  # <- this makes it act like a static site
    plan: free
    rootDir: AI_Resume_Optimizer
    buildCommand: npm install && npm run build
    staticPublishPath: dist  # change to 'build' if using CRA
    envVars:
      - key: VITE_API_URL
        value: https://ai-resume-backend.onrender.com
